services:
  wealthfolio:
    image: wealthfolio/wealthfolio:3.8.0
    labels:
      olares.service.type: Entrance
    ports:
      - "8088:8088"
    volumes:
      - wealthfolio-data:/data

volumes:
  wealthfolio-data:
    driver: local
